TARGET = ./task.out
SRC = ./tasks/3_1.cpp

.PHONY: all check build run clean

all: check build run memtest

check:
	./run_linters.sh $(SRC)

build:
	$(CXX) -g -fdiagnostics-color -Wall -Wextra -Werror -o $(TARGET) $(SRC)

run:
	$(TARGET)

clean:
	rm .out

memtest: build
	valgrind $(TARGET)
	rm .out
